package com.hospital.req.entity;

public enum HistoryAction {
    CREATE_DRAFT, SUBMIT,
    ADMIN_APPROVE, ADMIN_REJECT,
    REVIEW_APPROVE, REVIEW_REJECT,
    COMMENT_ADDED, ATTACHMENT_ADDED, EDIT,
    ATTACHMENT_DELETED, COMMENT_DELETED,
    MARK_COMPLETED, UNMARK_COMPLETED,
    MARK_WEEK_DONE, UNMARK_WEEK_DONE,
    MARK_MONTH_DONE, UNMARK_MONTH_DONE
}